# -*- coding: utf-8 -*-
"""selectKBest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BqzT2IKULAGi6r2khbv5uzmhI-EBVJYi
"""

from dataset import Dataset

import numpy as np
from typing import Callable

class SelectKBest:
#select features according to the k highest scores

    def __init__(self, dataset: Dataset, score_func: Callable, k: int):
        #score_func: function that return an array of scores for each feature (scores, p_values)
        #k: number of top features to select

        if k <= 0:
            raise ValueError("Sorry, k must be > 0")

        self.score_func = score_func
        self.k = k
        self.dataset = dataset

        self.F = None
        self.p = None


    def fit(self, dataset):
        #calculate the scores and p values

        scores, p_values = self.score_func(dataset)


    def transform(self, dataset):
        #transforms the dataset X by selecting the top k features based on their scores

        t = np.argsort(self.p)[:self.k]
        return X[:, t]


    def fit_transform(self, dataset):
        #calculates the scores and transforms the dataset by selecting the k highest scoring features
        
        X = dataset.X
        self.fit(dataset)
        
        return self.transform(X)

from f_regression import f_regression
import numpy as np


dataset = Dataset(X=np.array([[7, 2, 7],
                              [1, 0, 6],
                              [8, 0, 9]]),
                  y=np.array([1, 8, 3]),
                  features=["f1", "f2", "f3"],
                  label="y")

function = SelectKBest(dataset, score_func = f_regression, k = 1)
res = function.fit_transform(dataset)

print(res)

from google.colab import drive
drive.mount('/content/drive')